# Importing Packages
import os
import string
from eDOCr import keras_ocr
from eDOCr.keras_ocr_models import train_recognizer

# Fixing paths and alphabet
DIR = os.getcwd()
recognizer_basepath = os.path.join(DIR, 'eDOCr/Keras_OCR_models/models')
data_dir = './tests'
alphabet = string.digits + 'AaBCDRGHhMmnx' + '().,+-±:/°"⌀Ø'

# Number of autogenerated samples
samples = 10000

# Load white backgrounds and fonts
backgrounds = []
for i in range(0, samples):
    backgrounds.append(os.path.join('E:\\CXHCTL_Phuc\\Programs\\PythonCode\\pythonProject\\OCR_Test\\Programs\\eDOCr-master\\eDOCr-master\\eDOCr\\keras_ocr_models\\backgrounds\\0.jpg'))

fonts_dir = os.path.join(DIR, 'E:\\CXHCTL_Phuc\\Programs\\PythonCode\\pythonProject\\OCR_Test\\Programs\\eDOCr-master\\eDOCr-master\\eDOCr\\keras_ocr_models\\fonts')
fonts = []
for font_file in os.listdir(fonts_dir):
    font_path = os.path.join(fonts_dir, font_file)
    # Kiểm tra xem file font có tồn tại và có định dạng .ttf hoặc .otf
    if os.path.isfile(font_path) and (font_file.endswith('.ttf') or font_file.endswith('.otf')):
        fonts.append(font_path)

# Choose a pretrained model if you like

pretrained_model = None
#pretrained_model = os.path.join(recognizer_basepath,'recognizer_dimensions.h5')

# Start Training
train_recognizer.generate_n_train(alphabet, backgrounds, fonts, recognizer_basepath=recognizer_basepath, pretrained_model=pretrained_model)